[{"ContainerToolsException.Message":"Не удалось остановить приложение в контейнере. Сборка может завершиться неудачей, так как файлы используются. Сбой команды Docker с кодом завершения 1. Error response from daemon: container 9a4485e9aba88cdee6d8dc5d7cdb0ed733bab32cf9fbc53dbca1185ed53712d3 is not running","ContainerToolsException.ErrorCode":"CTP1006","ContainerToolsException.StackTrace":"   в Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.VisualStudio.Containers.Tools.Tasks.KillAppInsideContainer.<ExecuteCoreAsync>d__16.MoveNext()\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.VisualStudio.Containers.Tools.Tasks.ContainerBuildTask.<ExecuteAsync>d__26.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Сбой команды Docker с кодом завершения 1.\r\nError response from daemon: container 9a4485e9aba88cdee6d8dc5d7cdb0ed733bab32cf9fbc53dbca1185ed53712d3 is not running\r\n   в Microsoft.VisualStudio.Containers.Tools.Common.Client.DockerClient.<ExecAsync>d__18.MoveNext()\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.VisualStudio.Containers.Tools.Shared.ContainerLaunchManager.<KillAppInsideContainerAsync>d__4.MoveNext()\r\nКод ошибки: CTC1029\r\nСерьезность: Error\r\nКомандная строка: docker exec -i 9a4485e9aba88cdee6d8dc5d7cdb0ed733bab32cf9fbc53dbca1185ed53712d3 cmd /C \"IF EXIST C:\\remote_debugger\\x64\\utils\\KillProcess.exe C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe\"\r\nКод завершения команды: 1\r\nВыходные данные команды: \r\nОшибка команды: Error response from daemon: container 9a4485e9aba88cdee6d8dc5d7cdb0ed733bab32cf9fbc53dbca1185ed53712d3 is not running\r\n"}]